Requiring root

diff --git a/usr/bin/cernvm-fork b/usr/bin/cernvm-fork
--- a/usr/bin/cernvm-fork
+++ b/usr/bin/cernvm-fork
@@ -70,6 +70,9 @@ NAME=$1
 [ -z "$NAME" ] && echo "ERROR: Please specify an environment name! (Use --help for more info)" && exit 1
 [ "${NAME:0:1}" == "-" ] && echo "ERROR: Expecting fork name as first parameter! (Use --help for more info)" && exit 1
 
+# Require root
+[ $(id -u) -ne 0 ] && echo "ERROR: Only root can use this utility!" && exit 2
+
 # Get options from command-line
 options=$(getopt -o hDCt:nfcdra:o: -l help,destroy,console,tty:,new,nonic,fast,daemon,admin:,cvmfs:,run:,init:,ip:,log: -- "$@")
 if [ $? -ne 0 ]; then
